<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f36a06c4-498e-418c-8f3b-509d932bf7e4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Uber.ServiceDefaults\Uber.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Uber.Voyage.Application\Uber.Voyage.Application.csproj" />
    <ProjectReference Include="..\Uber.Voyage.Infrastructure\Uber.Voyage.Infrastructure.csproj" />
  </ItemGroup>

</Project>
